# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

affinity: {}

env: {}

image:
  repository: docker.io/homeassistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

ingress:
  enabled: false
  className: "nginx"
  annotations:
    # cert-manager.io/cluster-issuer:
    # cert-manager.io/issuer:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: "your-hostname"
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: "your-tls-secret"
    hosts:
    - "your-hostname"

nodeSelector: {}

podAnnotations: {}

podPriorityClassName: ""

podSecurityContext: {}
  # fsGroup: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  capabilities:
    add:
    - NET_RAW   # https://github.com/home-assistant/core/issues/62188#issuecomment-996801063
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  annotations: {}
  type: ClusterIP
  port: 8123

tolerations: []

volumeMounts: []
# - name: config
#   mountPath: /config

volumes: []
# - name: config
#   hostPath:
#     path: /etc/homeassistant
#     type: DirectoryOrCreate
